lib/gumroad_web/router.ex
defmodule GumroadWeb.Router do
  use GumroadWeb, :router

  import GumroadWeb.UserAuth

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_live_flash
    plug :put_root_layout, {GumroadWeb.LayoutView, :root}
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug :fetch_current_user
  end

  pipeline :api do
    plug :accepts, ["json"]
    plug CORSPlug, origin: "*"
  end

  scope "/", GumroadWeb do
    pipe_through :browser

    get "/", PageController, :index
  end

  # Other scopes may use custom stacks.
  scope "/api", GumroadWeb do
    pipe_through :api

    resources "/products", ProductController, except: [:new, :edit]
    resources "/reviews", ReviewController, except: [:new, :edit]
  end

  # Enables LiveDashboard only for development
  #
  # If you want to use the LiveDashboard in production, you should put
  # it behind authentication and allow only admins to access it.
  # If your application does not have an admins-only section yet,
  # you can use Plug.BasicAuth to set up some basic authentication
  # as long as you are also using SSL (which you should anyway).
  if Mix.env() in [:dev, :test] do
    import Phoenix.LiveDashboard.Router

    scope "/" do
      pipe_through :browser
      live_dashboard "/dashboard", metrics: GumroadWeb.Telemetry
    end
  end

  # Enables the Swoosh mailbox preview in development.
  #
  # Note that preview only shows emails that were sent by the same
  # node running the Phoenix server.
  if Mix.env() == :dev do
    scope "/dev" do
      pipe_through :browser

      forward "/mailbox", Plug.Swoosh.MailboxPreview
    end
  end

  ## Authentication routes

  scope "/", GumroadWeb do
    pipe_through [:browser, :redirect_if_user_is_authenticated]

    get "/users/register", UserRegistrationController, :new
    post "/users/register", UserRegistrationController, :create
    get "/users/log_in", UserSessionController, :new
    post "/users/log_in", UserSessionController, :create
    get "/users/reset_password", UserResetPasswordController, :new
    post "/users/reset_password", UserResetPasswordController, :create
    get "/users/reset_password/:token", UserResetPasswordController, :edit
    put "/users/reset_password/:token", UserResetPasswordController, :update
  end

  scope "/", GumroadWeb do
    pipe_through [:browser, :require_authenticated_user]

    get "/users/settings", UserSettingsController, :edit
    put "/users/settings", UserSettingsController, :update
    get "/users/settings/confirm_email/:token", UserSettingsController, :confirm_email

    live "/products", ProductLive.Index, :index
    live "/products/new", ProductLive.Index, :new
    live "/products/:id/edit", ProductLive.Index, :edit

    live "/products/:id", ProductLive.Show, :show
    live "/products/:id/review", ProductLive.Show, :add_review
    live "/products/:id/show/edit", ProductLive.Show, :edit

    live "/reviews", ReviewLive.Index, :index
    live "/reviews/new", ReviewLive.Index, :new
    live "/reviews/:id/edit", ReviewLive.Index, :edit

    live "/reviews/:id", ReviewLive.Show, :show
    live "/reviews/:id/show/edit", ReviewLive.Show, :edit
  end

  scope "/", GumroadWeb do
    pipe_through [:browser]

    delete "/users/log_out", UserSessionController, :delete
    get "/users/confirm", UserConfirmationController, :new
    post "/users/confirm", UserConfirmationController, :create
    get "/users/confirm/:token", UserConfirmationController, :edit
    post "/users/confirm/:token", UserConfirmationController, :update
  end
end

lib/gumroad_web/live/live_helpers.ex
defmodule GumroadWeb.LiveHelpers do
  import Phoenix.LiveView.Helpers

  @doc """
  Renders a component inside the `GumroadWeb.ModalComponent` component.

  The rendered modal receives a `:return_to` option to properly update
  the URL when the modal is closed.

  ## Examples

      <%= live_modal GumroadWeb.ProductLive.FormComponent,
        id: @product.id || :new,
        action: @live_action,
        product: @product,
        return_to: Routes.product_index_path(@socket, :index) %>
  """
  def live_modal(component, opts) do
    path = Keyword.fetch!(opts, :return_to)
    modal_opts = [id: :modal, return_to: path, component: component, opts: opts]
    live_component(GumroadWeb.ModalComponent, modal_opts)
  end
end

lib/gumroad_web/live/modal_component.ex
defmodule GumroadWeb.ModalComponent do
  use GumroadWeb, :live_component

  @impl true
  def render(assigns) do
    ~H"""
    <div class="fixed z-10 inset-0 overflow-y-auto" aria-labelledby="modal-title" role="dialog" aria-modal="true"
      id={@id}
      phx-capture-click="close"
      phx-window-keydown="close"
      phx-key="escape"
      phx-target={@myself}
      phx-page-loading
    >
      <div class="flex items-end justify-center min-h-screen pt-4 px-4 pb-20 text-center sm:block sm:p-0">
        <div class="fixed inset-0 bg-gray-500 bg-opacity-75 transition-opacity" aria-hidden="true" phx-capture-click="close" phx-target={@myself}></div>

        <!-- This element is to trick the browser into centering the modal contents. -->
        <span class="hidden sm:inline-block sm:align-middle sm:h-screen" aria-hidden="true">&#8203;</span>

        <div class="inline-block align-bottom bg-white rounded-lg px-4 pt-5 pb-4 text-left overflow-hidden shadow-xl transform transition-all sm:my-8 sm:align-middle sm:max-w-sm sm:w-full sm:p-6">
          <%= live_component @component, @opts %>
        </div>
      </div>
    </div>
    """
  end

  @impl true
  def handle_event("close", _, socket) do
    {:noreply, push_patch(socket, to: socket.assigns.return_to)}
  end
end

lib/gumroad_web/live/product_live/form_component.ex
defmodule GumroadWeb.ProductLive.FormComponent do
  use GumroadWeb, :live_component

  alias Gumroad.Products

  @impl true
  def update(%{product: product} = assigns, socket) do
    changeset = Products.change_product(product)

    {:ok,
     socket
     |> assign(assigns)
     |> assign(:changeset, changeset)}
  end

  @impl true
  def handle_event("validate", %{"product" => product_params}, socket) do
    changeset =
      socket.assigns.product
      |> Products.change_product(product_params)
      |> Map.put(:action, :validate)

    {:noreply, assign(socket, :changeset, changeset)}
  end

  def handle_event("save", %{"product" => product_params}, socket) do
    save_product(socket, socket.assigns.action, product_params)
  end

  defp save_product(socket, :edit, product_params) do
    case Products.update_product(socket.assigns.product, product_params) do
      {:ok, _product} ->
        {:noreply,
         socket
         |> put_flash(:info, "Product updated successfully")
         |> push_redirect(to: socket.assigns.return_to)}

      {:error, %Ecto.Changeset{} = changeset} ->
        {:noreply, assign(socket, :changeset, changeset)}
    end
  end

  defp save_product(socket, :new, product_params) do
    case Products.create_product(product_params) do
      {:ok, _product} ->
        {:noreply,
         socket
         |> put_flash(:info, "Product created successfully")
         |> push_redirect(to: socket.assigns.return_to)}

      {:error, %Ecto.Changeset{} = changeset} ->
        {:noreply, assign(socket, changeset: changeset)}
    end
  end
end

lib/gumroad_web/live/product_live/index.ex
defmodule GumroadWeb.ProductLive.Index do
  use GumroadWeb, :live_view

  alias Gumroad.Products
  alias Gumroad.Products.Product

  @impl true
  def mount(_params, _session, socket) do
    {:ok, assign(socket, :products, list_products())}
  end

  @impl true
  def handle_params(params, _url, socket) do
    {:noreply, apply_action(socket, socket.assigns.live_action, params)}
  end

  defp apply_action(socket, :edit, %{"id" => id}) do
    socket
    |> assign(:page_title, "Edit Product")
    |> assign(:product, Products.get_product!(id))
  end

  defp apply_action(socket, :new, _params) do
    socket
    |> assign(:page_title, "New Product")
    |> assign(:product, %Product{})
  end

  defp apply_action(socket, :index, _params) do
    socket
    |> assign(:page_title, "Listing Products")
    |> assign(:product, nil)
  end

  @impl true
  def handle_event("delete", %{"id" => id}, socket) do
    product = Products.get_product!(id)
    {:ok, _} = Products.delete_product(product)

    {:noreply, assign(socket, :products, list_products())}
  end

  defp list_products do
    Products.list_products()
  end
end

lib/gumroad_web/live/product_live/show.ex
defmodule GumroadWeb.ProductLive.Show do
  use GumroadWeb, :live_view

  alias Gumroad.Products
  alias Gumroad.Products.Review

  @impl true
  def mount(_params, _session, socket) do
    {:ok, socket}
  end

  @impl true
  def handle_params(%{"id" => id}, _, socket) do
    product = Products.get_product!(id)
    reviews = Products.list_reviews_for_product(product)
    average_rating = Float.round(Enum.sum(Enum.map(reviews, & &1.rating)) / length(reviews), 2)

    {:noreply,
     socket
     |> assign(:product, product)
     |> assign(:page_title, page_title(socket.assigns.live_action))
     |> assign(:review, %Review{product_id: product.id})
     |> assign(:reviews, reviews)
     |> assign(:average_rating, average_rating)}
  end

  defp page_title(:show), do: "Show Product"
  defp page_title(:edit), do: "Edit Product"
  defp page_title(:add_review), do: "What's your rating?"
end

lib/gumroad_web/live/review_live/form_component.ex
defmodule GumroadWeb.ReviewLive.FormComponent do
  use GumroadWeb, :live_component

  alias Gumroad.Products

  @impl true
  def update(%{review: review} = assigns, socket) do
    changeset = Products.change_review(review)

    {:ok,
     socket
     |> assign(assigns)
     |> assign(:changeset, changeset)
     |> assign(:products, Products.list_products())}
  end

  @impl true
  def handle_event("validate", %{"review" => review_params}, socket) do
    changeset =
      socket.assigns.review
      |> Products.change_review(review_params)
      |> Map.put(:action, :validate)

    {:noreply, assign(socket, :changeset, changeset)}
  end

  def handle_event("save", %{"review" => review_params}, socket) do
    save_review(socket, socket.assigns.action, review_params)
  end

  defp save_review(socket, :add_review, review_params) do
    params = Map.merge(%{"product_id" => socket.assigns.product.id}, review_params)

    case Products.create_review(params) do
      {:ok, _review} ->
        {:noreply,
         socket
         |> put_flash(:info, "Review created successfully")
         |> push_redirect(to: socket.assigns.return_to)}

      {:error, %Ecto.Changeset{} = changeset} ->
        {:noreply, assign(socket, changeset: changeset)}
    end
  end

  defp save_review(socket, :edit, review_params) do
    case Products.update_review(socket.assigns.review, review_params) do
      {:ok, _review} ->
        {:noreply,
         socket
         |> put_flash(:info, "Review updated successfully")
         |> push_redirect(to: socket.assigns.return_to)}

      {:error, %Ecto.Changeset{} = changeset} ->
        {:noreply, assign(socket, :changeset, changeset)}
    end
  end

  defp save_review(socket, :new, review_params) do
    case Products.create_review(review_params) do
      {:ok, _review} ->
        {:noreply,
         socket
         |> put_flash(:info, "Review created successfully")
         |> push_redirect(to: socket.assigns.return_to)}

      {:error, %Ecto.Changeset{} = changeset} ->
        {:noreply, assign(socket, changeset: changeset)}
    end
  end
end

lib/gumroad_web/live/review_live/index.ex
defmodule GumroadWeb.ReviewLive.Index do
  use GumroadWeb, :live_view

  alias Gumroad.Products
  alias Gumroad.Products.Review

  @impl true
  def mount(_params, _session, socket) do
    {:ok, assign(socket, :reviews, list_reviews())}
  end

  @impl true
  def handle_params(params, _url, socket) do
    {:noreply, apply_action(socket, socket.assigns.live_action, params)}
  end

  defp apply_action(socket, :edit, %{"id" => id}) do
    socket
    |> assign(:page_title, "Edit Review")
    |> assign(:review, Products.get_review!(id))
  end

  defp apply_action(socket, :new, _params) do
    socket
    |> assign(:page_title, "New Review")
    |> assign(:review, %Review{})
  end

  defp apply_action(socket, :index, _params) do
    socket
    |> assign(:page_title, "Listing Reviews")
    |> assign(:review, nil)
  end

  @impl true
  def handle_event("delete", %{"id" => id}, socket) do
    review = Products.get_review!(id)
    {:ok, _} = Products.delete_review(review)

    {:noreply, assign(socket, :reviews, list_reviews())}
  end

  defp list_reviews do
    Products.list_reviews_with_product()
  end
end

lib/gumroad_web/live/review_live/rating_component.ex
defmodule GumroadWeb.ReviewLive.RatingComponent do
  use GumroadWeb, :live_component
end

lib/gumroad_web/live/review_live/review_component.ex
defmodule GumroadWeb.ReviewLive.ReviewComponent do
  use GumroadWeb, :live_component
end

lib/gumroad_web/live/review_live/show.ex
defmodule GumroadWeb.ReviewLive.Show do
  use GumroadWeb, :live_view

  alias Gumroad.Products

  @impl true
  def mount(_params, _session, socket) do
    {:ok, socket}
  end

  @impl true
  def handle_params(%{"id" => id}, _, socket) do
    {:noreply,
     socket
     |> assign(:page_title, page_title(socket.assigns.live_action))
     |> assign(:review, Products.get_review!(id))}
  end

  defp page_title(:show), do: "Show Review"
  defp page_title(:edit), do: "Edit Review"
end

lib/gumroad_web/live/product_live/form_component.html.heex
<div class="grid gap-8">
  <h2 class="header"><%= @title %></h2>

  <.form
    let={f}
    for={@changeset}
    id="product-form"
    phx-target={@myself}
    phx-change="validate"
    phx-submit="save"
    class="grid gap-8"
    >

    <div>
      <%= label f, :name, class: "block text-sm font-medium text-gray-700 mb-1" %>
      <%= text_input f, :name %>
      <p class="block mt-2 text-sm text-red-600">
        <%= error_tag f, :name %>
      </p>
    </div>

    <div>
      <%= label f, :description, class: "block text-sm font-medium text-gray-700 mb-1" %>
      <%= text_input f, :description %>
      <p class="block mt-2 text-sm text-red-600">
        <%= error_tag f, :description %>
      </p>
    </div>

    <div>
      <%= label f, :price, class: "block text-sm font-medium text-gray-700 mb-1" %>
      <%= number_input f, :price, step: "any" %>
      <p class="block mt-2 text-sm text-red-600">
        <%= error_tag f, :price %>
      </p>
    </div>

    <div>
      <%= submit "Save", phx_disable_with: "Saving...", class: "button button-primary" %>
    </div>
  </.form>
</div>

lib/gumroad_web/live/product_live/index.html.heex
<div class="grid gap-8">
  <h1 class="header">Listing Products</h1>

  <%= if @live_action in [:new, :edit] do %>
    <%= live_modal GumroadWeb.ProductLive.FormComponent,
      id: @product.id || :new,
      title: @page_title,
      action: @live_action,
      product: @product,
      return_to: Routes.product_index_path(@socket, :index) %>
  <% end %>

  <table>
    <thead>
      <tr>
        <th>Name</th>
        <th>Description</th>
        <th>Price</th>

        <th></th>
      </tr>
    </thead>
    <tbody id="products">
      <%= for product <- @products do %>
        <tr id={"product-#{product.id}"}>
          <td><%= product.name %></td>
          <td><%= product.description %></td>
          <td><%= product.price %></td>

          <td>
            <span class="button button-primary"><%= live_redirect "Show", to: Routes.product_show_path(@socket, :show, product) %></span>
            <span class="button button-secondary"><%= live_patch "Edit", to: Routes.product_index_path(@socket, :edit, product) %></span>
            <span class="button button-danger"><%= link "Delete", to: "#", phx_click: "delete", phx_value_id: product.id, data: [confirm: "Are you sure?"] %></span>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <div>
    <span class="button button-primary"><%= live_patch "New Product", to: Routes.product_index_path(@socket, :new) %></span>
  </div>
</div>

lib/gumroad_web/live/product_live/show.html.heex
<div class="max-w-screen-sm mx-auto py-12">
  <%= if @live_action in [:edit] do %>
    <%= live_modal GumroadWeb.ProductLive.FormComponent,
      id: @product.id,
      title: @page_title,
      action: @live_action,
      product: @product,
      return_to: Routes.product_show_path(@socket, :show, @product) %>
  <% end %>
  <%= if @live_action in [:add_review] do %>
    <%= live_modal GumroadWeb.ReviewLive.FormComponent,
      id: @product.id,
      title: @page_title,
      action: @live_action,
      product: @product,
      review: @review,
      return_to: Routes.product_show_path(@socket, :show, @product) %>
  <% end %>
  <div class="space-y-6">
    <h1 class="text-4xl font-extrabold text-gray-900"><%= @product.name %></h1>
    <div class="flex items-center justify-between text-xl">
      <div>
        <h2 class="sr-only">Reviews</h2>
        <div class="flex gap-2 items-center">
          <p class="text-gray-900 font-medium text-3xl">
            <%= Float.round(@average_rating, 1) %>
            <span class="sr-only"> out of 5 stars</span>
          </p>
          <div class="flex items-center">
          <%= for _ <- 1..round(@average_rating) do %>
            <!--
              Heroicon name: solid/star

              Active: "text-yellow-400", Inactive: "text-gray-200"
            -->
            <svg class="text-yellow-400 h-8 w-8 flex-shrink-0" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor" aria-hidden="true">
              <path d="M9.049 2.927c.3-.921 1.603-.921 1.902 0l1.07 3.292a1 1 0 00.95.69h3.462c.969 0 1.371 1.24.588 1.81l-2.8 2.034a1 1 0 00-.364 1.118l1.07 3.292c.3.921-.755 1.688-1.54 1.118l-2.8-2.034a1 1 0 00-1.175 0l-2.8 2.034c-.784.57-1.838-.197-1.539-1.118l1.07-3.292a1 1 0 00-.364-1.118L2.98 8.72c-.783-.57-.38-1.81.588-1.81h3.461a1 1 0 00.951-.69l1.07-3.292z" />
            </svg>
          <% end %>
          <%= for _ <- 1..round(5 - @average_rating) do %>
            <svg class="text-gray-200 h-8 w-8 flex-shrink-0" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor" aria-hidden="true">
              <path d="M9.049 2.927c.3-.921 1.603-.921 1.902 0l1.07 3.292a1 1 0 00.95.69h3.462c.969 0 1.371 1.24.588 1.81l-2.8 2.034a1 1 0 00-.364 1.118l1.07 3.292c.3.921-.755 1.688-1.54 1.118l-2.8-2.034a1 1 0 00-1.175 0l-2.8 2.034c-.784.57-1.838-.197-1.539-1.118l1.07-3.292a1 1 0 00-.364-1.118L2.98 8.72c-.783-.57-.38-1.81.588-1.81h3.461a1 1 0 00.951-.69l1.07-3.292z" />
            </svg>
            <% end %>
          </div>
        </div>
      </div>
      <div>
          <span class="button button-secondary"><%= live_patch "Add review", to: Routes.product_show_path(@socket, :add_review, @product.id) %></span>
      </div>
    </div>
  </div>
  <div class="border border-t border-gray-200 mt-8"></div>
  <div class="mt-8">
    <div class="px-4 py-5 sm:p-0">
      <h1 class="text-3xl font-bold text-gray-900">Reviews</h1>
      <dl class="space-y-4 mt-6">
        <%= for review <- @reviews do %>
          <%= live_component(GumroadWeb.ReviewLive.ReviewComponent, review: review) %>
        <% end %>
      </dl>
    </div>
  </div>
</div>