lib/gumroad_web/router.ex
defmodule GumroadWeb.Router do
  use GumroadWeb, :router

  import GumroadWeb.UserAuth

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_live_flash
    plug :put_root_layout, {GumroadWeb.LayoutView, :root}
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug :fetch_current_user
  end

  pipeline :api do
    plug :accepts, ["json"]
    plug CORSPlug, origin: "*"
  end

  scope "/", GumroadWeb do
    pipe_through :browser

    get "/", PageController, :index
  end

  # Other scopes may use custom stacks.
  scope "/api", GumroadWeb do
    pipe_through :api

    resources "/products", ProductController, except: [:new, :edit]
    resources "/reviews", ReviewController, except: [:new, :edit]
  end

  # Enables LiveDashboard only for development
  #
  # If you want to use the LiveDashboard in production, you should put
  # it behind authentication and allow only admins to access it.
  # If your application does not have an admins-only section yet,
  # you can use Plug.BasicAuth to set up some basic authentication
  # as long as you are also using SSL (which you should anyway).
  if Mix.env() in [:dev, :test] do
    import Phoenix.LiveDashboard.Router

    scope "/" do
      pipe_through :browser
      live_dashboard "/dashboard", metrics: GumroadWeb.Telemetry
    end
  end

  # Enables the Swoosh mailbox preview in development.
  #
  # Note that preview only shows emails that were sent by the same
  # node running the Phoenix server.
  if Mix.env() == :dev do
    scope "/dev" do
      pipe_through :browser

      forward "/mailbox", Plug.Swoosh.MailboxPreview
    end
  end

  ## Authentication routes

  scope "/", GumroadWeb do
    pipe_through [:browser, :redirect_if_user_is_authenticated]

    get "/users/register", UserRegistrationController, :new
    post "/users/register", UserRegistrationController, :create
    get "/users/log_in", UserSessionController, :new
    post "/users/log_in", UserSessionController, :create
    get "/users/reset_password", UserResetPasswordController, :new
    post "/users/reset_password", UserResetPasswordController, :create
    get "/users/reset_password/:token", UserResetPasswordController, :edit
    put "/users/reset_password/:token", UserResetPasswordController, :update
  end

  scope "/", GumroadWeb do
    pipe_through [:browser, :require_authenticated_user]

    get "/users/settings", UserSettingsController, :edit
    put "/users/settings", UserSettingsController, :update
    get "/users/settings/confirm_email/:token", UserSettingsController, :confirm_email

    live "/products", ProductLive.Index, :index
    live "/products/new", ProductLive.Index, :new
    live "/products/:id/edit", ProductLive.Index, :edit

    live "/products/:id", ProductLive.Show, :show
    live "/products/:id/review", ProductLive.Show, :add_review
    live "/products/:id/show/edit", ProductLive.Show, :edit

    live "/reviews", ReviewLive.Index, :index
    live "/reviews/new", ReviewLive.Index, :new
    live "/reviews/:id/edit", ReviewLive.Index, :edit

    live "/reviews/:id", ReviewLive.Show, :show
    live "/reviews/:id/show/edit", ReviewLive.Show, :edit
  end

  scope "/", GumroadWeb do
    pipe_through [:browser]

    delete "/users/log_out", UserSessionController, :delete
    get "/users/confirm", UserConfirmationController, :new
    post "/users/confirm", UserConfirmationController, :create
    get "/users/confirm/:token", UserConfirmationController, :edit
    post "/users/confirm/:token", UserConfirmationController, :update
  end
end

lib/gumroad_web/live/live_helpers.ex
defmodule GumroadWeb.LiveHelpers do
  import Phoenix.LiveView.Helpers

  @doc """
  Renders a component inside the `GumroadWeb.ModalComponent` component.

  The rendered modal receives a `:return_to` option to properly update
  the URL when the modal is closed.

  ## Examples

      <%= live_modal GumroadWeb.ProductLive.FormComponent,
        id: @product.id || :new,
        action: @live_action,
        product: @product,
        return_to: Routes.product_index_path(@socket, :index) %>
  """
  def live_modal(component, opts) do
    path = Keyword.fetch!(opts, :return_to)
    modal_opts = [id: :modal, return_to: path, component: component, opts: opts]
    live_component(GumroadWeb.ModalComponent, modal_opts)
  end
end

lib/gumroad_web/live/modal_component.ex
defmodule GumroadWeb.ModalComponent do
  use GumroadWeb, :live_component

  @impl true
  def render(assigns) do
    ~H"""
    <div class="fixed z-10 inset-0 overflow-y-auto" aria-labelledby="modal-title" role="dialog" aria-modal="true"
      id={@id}
      phx-capture-click="close"
      phx-window-keydown="close"
      phx-key="escape"
      phx-target={@myself}
      phx-page-loading
    >
      <div class="flex items-end justify-center min-h-screen pt-4 px-4 pb-20 text-center sm:block sm:p-0">
        <div class="fixed inset-0 bg-gray-500 bg-opacity-75 transition-opacity" aria-hidden="true" phx-capture-click="close" phx-target={@myself}></div>

        <!-- This element is to trick the browser into centering the modal contents. -->
        <span class="hidden sm:inline-block sm:align-middle sm:h-screen" aria-hidden="true">&#8203;</span>

        <div class="inline-block align-bottom bg-white rounded-lg px-4 pt-5 pb-4 text-left overflow-hidden shadow-xl transform transition-all sm:my-8 sm:align-middle sm:max-w-sm sm:w-full sm:p-6">
          <%= live_component @component, @opts %>
        </div>
      </div>
    </div>
    """
  end

  @impl true
  def handle_event("close", _, socket) do
    {:noreply, push_patch(socket, to: socket.assigns.return_to)}
  end
end

lib/gumroad_web/live/product_live/form_component.ex
defmodule GumroadWeb.ProductLive.FormComponent do
  use GumroadWeb, :live_component

  alias Gumroad.Products

  @impl true
  def update(%{product: product} = assigns, socket) do
    changeset = Products.change_product(product)

    {:ok,
     socket
     |> assign(assigns)
     |> assign(:changeset, changeset)}
  end

  @impl true
  def handle_event("validate", %{"product" => product_params}, socket) do
    changeset =
      socket.assigns.product
      |> Products.change_product(product_params)
      |> Map.put(:action, :validate)

    {:noreply, assign(socket, :changeset, changeset)}
  end

  def handle_event("save", %{"product" => product_params}, socket) do
    save_product(socket, socket.assigns.action, product_params)
  end

  defp save_product(socket, :edit, product_params) do
    case Products.update_product(socket.assigns.product, product_params) do
      {:ok, _product} ->
        {:noreply,
         socket
         |> put_flash(:info, "Product updated successfully")
         |> push_redirect(to: socket.assigns.return_to)}

      {:error, %Ecto.Changeset{} = changeset} ->
        {:noreply, assign(socket, :changeset, changeset)}
    end
  end

  defp save_product(socket, :new, product_params) do
    case Products.create_product(product_params) do
      {:ok, _product} ->
        {:noreply,
         socket
         |> put_flash(:info, "Product created successfully")
         |> push_redirect(to: socket.assigns.return_to)}

      {:error, %Ecto.Changeset{} = changeset} ->
        {:noreply, assign(socket, changeset: changeset)}
    end
  end
end

lib/gumroad_web/live/product_live/index.ex
defmodule GumroadWeb.ProductLive.Index do
  use GumroadWeb, :live_view

  alias Gumroad.Products
  alias Gumroad.Products.Product

  @impl true
  def mount(_params, _session, socket) do
    {:ok, assign(socket, :products, list_products())}
  end

  @impl true
  def handle_params(params, _url, socket) do
    {:noreply, apply_action(socket, socket.assigns.live_action, params)}
  end

  defp apply_action(socket, :edit, %{"id" => id}) do
    socket
    |> assign(:page_title, "Edit Product")
    |> assign(:product, Products.get_product!(id))
  end

  defp apply_action(socket, :new, _params) do
    socket
    |> assign(:page_title, "New Product")
    |> assign(:product, %Product{})
  end

  defp apply_action(socket, :index, _params) do
    socket
    |> assign(:page_title, "Listing Products")
    |> assign(:product, nil)
  end

  @impl true
  def handle_event("delete", %{"id" => id}, socket) do
    product = Products.get_product!(id)
    {:ok, _} = Products.delete_product(product)

    {:noreply, assign(socket, :products, list_products())}
  end

  defp list_products do
    Products.list_products()
  end
end

lib/gumroad_web/live/product_live/show.ex
defmodule GumroadWeb.ProductLive.Show do
  use GumroadWeb, :live_view

  alias Gumroad.Products
  alias Gumroad.Products.Review

  @impl true
  def mount(_params, _session, socket) do
    {:ok, socket}
  end

  @impl true
  def handle_params(%{"id" => id}, _, socket) do
    product = Products.get_product!(id)
    reviews = Products.list_reviews_for_product(product)
    average_rating = Float.round(Enum.sum(Enum.map(reviews, & &1.rating)) / length(reviews), 2)

    {:noreply,
     socket
     |> assign(:product, product)
     |> assign(:page_title, page_title(socket.assigns.live_action))
     |> assign(:review, %Review{product_id: product.id})
     |> assign(:reviews, reviews)
     |> assign(:average_rating, average_rating)}
  end

  defp page_title(:show), do: "Show Product"
  defp page_title(:edit), do: "Edit Product"
  defp page_title(:add_review), do: "What's your rating?"
end

lib/gumroad_web/live/review_live/form_component.ex
defmodule GumroadWeb.ReviewLive.FormComponent do
  use GumroadWeb, :live_component

  alias Gumroad.Products

  @impl true
  def update(%{review: review} = assigns, socket) do
    changeset = Products.change_review(review)

    {:ok,
     socket
     |> assign(assigns)
     |> assign(:changeset, changeset)
     |> assign(:products, Products.list_products())}
  end

  @impl true
  def handle_event("validate", %{"review" => review_params}, socket) do
    changeset =
      socket.assigns.review
      |> Products.change_review(review_params)
      |> Map.put(:action, :validate)

    {:noreply, assign(socket, :changeset, changeset)}
  end

  def handle_event("save", %{"review" => review_params}, socket) do
    save_review(socket, socket.assigns.action, review_params)
  end

  defp save_review(socket, :add_review, review_params) do
    params = Map.merge(%{"product_id" => socket.assigns.product.id}, review_params)

    case Products.create_review(params) do
      {:ok, _review} ->
        {:noreply,
         socket
         |> put_flash(:info, "Review created successfully")
         |> push_redirect(to: socket.assigns.return_to)}

      {:error, %Ecto.Changeset{} = changeset} ->
        {:noreply, assign(socket, changeset: changeset)}
    end
  end

  defp save_review(socket, :edit, review_params) do
    case Products.update_review(socket.assigns.review, review_params) do
      {:ok, _review} ->
        {:noreply,
         socket
         |> put_flash(:info, "Review updated successfully")
         |> push_redirect(to: socket.assigns.return_to)}

      {:error, %Ecto.Changeset{} = changeset} ->
        {:noreply, assign(socket, :changeset, changeset)}
    end
  end

  defp save_review(socket, :new, review_params) do
    case Products.create_review(review_params) do
      {:ok, _review} ->
        {:noreply,
         socket
         |> put_flash(:info, "Review created successfully")
         |> push_redirect(to: socket.assigns.return_to)}

      {:error, %Ecto.Changeset{} = changeset} ->
        {:noreply, assign(socket, changeset: changeset)}
    end
  end
end

lib/gumroad_web/live/review_live/index.ex
defmodule GumroadWeb.ReviewLive.Index do
  use GumroadWeb, :live_view

  alias Gumroad.Products
  alias Gumroad.Products.Review

  @impl true
  def mount(_params, _session, socket) do
    {:ok, assign(socket, :reviews, list_reviews())}
  end

  @impl true
  def handle_params(params, _url, socket) do
    {:noreply, apply_action(socket, socket.assigns.live_action, params)}
  end

  defp apply_action(socket, :edit, %{"id" => id}) do
    socket
    |> assign(:page_title, "Edit Review")
    |> assign(:review, Products.get_review!(id))
  end

  defp apply_action(socket, :new, _params) do
    socket
    |> assign(:page_title, "New Review")
    |> assign(:review, %Review{})
  end

  defp apply_action(socket, :index, _params) do
    socket
    |> assign(:page_title, "Listing Reviews")
    |> assign(:review, nil)
  end

  @impl true
  def handle_event("delete", %{"id" => id}, socket) do
    review = Products.get_review!(id)
    {:ok, _} = Products.delete_review(review)

    {:noreply, assign(socket, :reviews, list_reviews())}
  end

  defp list_reviews do
    Products.list_reviews_with_product()
  end
end

lib/gumroad_web/live/review_live/rating_component.ex
defmodule GumroadWeb.ReviewLive.RatingComponent do
  use GumroadWeb, :live_component
end

lib/gumroad_web/live/review_live/review_component.ex
defmodule GumroadWeb.ReviewLive.ReviewComponent do
  use GumroadWeb, :live_component
end

lib/gumroad_web/live/review_live/show.ex
defmodule GumroadWeb.ReviewLive.Show do
  use GumroadWeb, :live_view

  alias Gumroad.Products

  @impl true
  def mount(_params, _session, socket) do
    {:ok, socket}
  end

  @impl true
  def handle_params(%{"id" => id}, _, socket) do
    {:noreply,
     socket
     |> assign(:page_title, page_title(socket.assigns.live_action))
     |> assign(:review, Products.get_review!(id))}
  end

  defp page_title(:show), do: "Show Review"
  defp page_title(:edit), do: "Edit Review"
end

lib/gumroad_web/live/review_live/form_component.html.heex
<div class="grid gap-8">
  <h2 class="header"><%= @title %></h2>

  <.form
    let={f}
    for={@changeset}
    id="review-form"
    phx-target={@myself}
    phx-change="validate"
    phx-submit="save"
    class="grid gap-8"
    >

    <%= text_input f, :rating, class: "hidden" %>
    <%= live_component(GumroadWeb.ReviewLive.RatingComponent, form: f, field: :rating) %>
    <div>
      <%= label f, :description, class: "block text-sm font-medium text-gray-700 mb-1" %>
      <%= textarea f, :description, placeholder: "Start typing...", class: "max-w-lg shadow-sm block w-full focus:ring-cyan-500 focus:border-cyan-500 sm:text-sm border border-gray-300 rounded-md" %>
      <p class="block mt-2 text-sm text-red-600">
        <%= error_tag f, :description %>
      </p>
    </div>

    <%= if @action != :add_review do %>
    <div>
      <%= label f, :product_id, class: "block text-sm font-medium text-gray-700 mb-1" %>
      <%= select f, :product_id, Enum.map(@products, fn p -> {p.name, p.id} end) %>
      <p class="block mt-2 text-sm text-red-600">
        <%= error_tag f, :product_id %>
      </p>
    </div>
    <% end %>

    <div>
      <%= submit "Submit review", phx_disable_with: "Saving...", class: "button button-secondary" %>
    </div>
  </.form>
</div>

lib/gumroad_web/live/review_live/index.html.heex
<div class="grid gap-8">
  <h1 class="header">Listing Reviews</h1>

  <%= if @live_action in [:new, :edit] do %>
    <%= live_modal GumroadWeb.ReviewLive.FormComponent,
      id: @review.id || :new,
      title: @page_title,
      action: @live_action,
      review: @review,
      return_to: Routes.review_index_path(@socket, :index) %>
  <% end %>

  <table>
    <thead>
      <tr>
        <th>Product</th>
        <th>Description</th>
        <th>Rating</th>

        <th></th>
      </tr>
    </thead>
    <tbody id="reviews">
      <%= for review <- @reviews do %>
        <tr id={"review-#{review.id}"}>
          <td><%= review.product.name %></td>
          <td><%= review.description %></td>
          <td><%= review.rating %></td>

          <td>
            <span class="button button-primary"><%= live_redirect "Show", to: Routes.review_show_path(@socket, :show, review) %></span>
            <span class="button button-secondary"><%= live_patch "Edit", to: Routes.review_index_path(@socket, :edit, review) %></span>
            <span class="button button-danger"><%= link "Delete", to: "#", phx_click: "delete", phx_value_id: review.id, data: [confirm: "Are you sure?"] %></span>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <div>
    <span class="button button-primary"><%= live_patch "New Review", to: Routes.review_index_path(@socket, :new) %></span>
  </div>
</div>

lib/gumroad_web/live/review_live/rating_component.html.heex
<div>
	<%= label @form, @field, class: "block text-sm font-medium text-gray-700 mb-1" %>
	<div class="rate flex">
		<input type="radio" id="rating-1" value={1} name={"#{@form.name}[#{@field}]"} />
		<label for="rating-1" title="1 star">
			<svg class={if Map.get(@form.source.changes, :rating, 0) >= 1.0, do: "text-yellow-400 h-8 w-8 flex-shrink-0", else: "text-gray-200 h-8 w-8 flex-shrink-0"} xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor" aria-hidden="true">
				<path d="M9.049 2.927c.3-.921 1.603-.921 1.902 0l1.07 3.292a1 1 0 00.95.69h3.462c.969 0 1.371 1.24.588 1.81l-2.8 2.034a1 1 0 00-.364 1.118l1.07 3.292c.3.921-.755 1.688-1.54 1.118l-2.8-2.034a1 1 0 00-1.175 0l-2.8 2.034c-.784.57-1.838-.197-1.539-1.118l1.07-3.292a1 1 0 00-.364-1.118L2.98 8.72c-.783-.57-.38-1.81.588-1.81h3.461a1 1 0 00.951-.69l1.07-3.292z" />
			</svg>
		</label>

		<input type="radio" id="rating-2" name={"#{@form.name}[#{@field}]"} value="2" />
		<label for="rating-2" title="2 star">
			<svg class={if Map.get(@form.source.changes, :rating, 0) >= 2.0, do: "text-yellow-400 h-8 w-8 flex-shrink-0", else: "text-gray-200 h-8 w-8 flex-shrink-0"} xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor" aria-hidden="true">
				<path d="M9.049 2.927c.3-.921 1.603-.921 1.902 0l1.07 3.292a1 1 0 00.95.69h3.462c.969 0 1.371 1.24.588 1.81l-2.8 2.034a1 1 0 00-.364 1.118l1.07 3.292c.3.921-.755 1.688-1.54 1.118l-2.8-2.034a1 1 0 00-1.175 0l-2.8 2.034c-.784.57-1.838-.197-1.539-1.118l1.07-3.292a1 1 0 00-.364-1.118L2.98 8.72c-.783-.57-.38-1.81.588-1.81h3.461a1 1 0 00.951-.69l1.07-3.292z" />
			</svg>
		</label>

		<input type="radio" id="rating-3" name={"#{@form.name}[#{@field}]"} value="3" />
		<label for="rating-3" title="3 star">
			<svg class={if Map.get(@form.source.changes, :rating, 0) >= 3.0, do: "text-yellow-400 h-8 w-8 flex-shrink-0", else: "text-gray-200 h-8 w-8 flex-shrink-0"} xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor" aria-hidden="true">
				<path d="M9.049 2.927c.3-.921 1.603-.921 1.902 0l1.07 3.292a1 1 0 00.95.69h3.462c.969 0 1.371 1.24.588 1.81l-2.8 2.034a1 1 0 00-.364 1.118l1.07 3.292c.3.921-.755 1.688-1.54 1.118l-2.8-2.034a1 1 0 00-1.175 0l-2.8 2.034c-.784.57-1.838-.197-1.539-1.118l1.07-3.292a1 1 0 00-.364-1.118L2.98 8.72c-.783-.57-.38-1.81.588-1.81h3.461a1 1 0 00.951-.69l1.07-3.292z" />
			</svg>
		</label>

		<input type="radio" id="rating-4" name={"#{@form.name}[#{@field}]"} value="4" />
		<label for="rating-4" title="4 star">
			<svg class={if Map.get(@form.source.changes, :rating, 0) >= 4.0, do: "text-yellow-400 h-8 w-8 flex-shrink-0", else: "text-gray-200 h-8 w-8 flex-shrink-0"} xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor" aria-hidden="true">
				<path d="M9.049 2.927c.3-.921 1.603-.921 1.902 0l1.07 3.292a1 1 0 00.95.69h3.462c.969 0 1.371 1.24.588 1.81l-2.8 2.034a1 1 0 00-.364 1.118l1.07 3.292c.3.921-.755 1.688-1.54 1.118l-2.8-2.034a1 1 0 00-1.175 0l-2.8 2.034c-.784.57-1.838-.197-1.539-1.118l1.07-3.292a1 1 0 00-.364-1.118L2.98 8.72c-.783-.57-.38-1.81.588-1.81h3.461a1 1 0 00.951-.69l1.07-3.292z" />
			</svg>

		</label>

		<input type="radio" id="rating-5" name={"#{@form.name}[#{@field}]"} value="5" />
		<label for="rating-5" title="5 star">
			<svg class={if Map.get(@form.source.changes, :rating, 0) >= 5.0, do: "text-yellow-400 h-8 w-8 flex-shrink-0", else: "text-gray-200 h-8 w-8 flex-shrink-0"} xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor" aria-hidden="true">
				<path d="M9.049 2.927c.3-.921 1.603-.921 1.902 0l1.07 3.292a1 1 0 00.95.69h3.462c.969 0 1.371 1.24.588 1.81l-2.8 2.034a1 1 0 00-.364 1.118l1.07 3.292c.3.921-.755 1.688-1.54 1.118l-2.8-2.034a1 1 0 00-1.175 0l-2.8 2.034c-.784.57-1.838-.197-1.539-1.118l1.07-3.292a1 1 0 00-.364-1.118L2.98 8.72c-.783-.57-.38-1.81.588-1.81h3.461a1 1 0 00.951-.69l1.07-3.292z" />
			</svg>

		</label>

	</div>
	<p class="block mt-2 text-sm text-red-600">
		<%= error_tag @form, @field %>
	</p>
</div>

lib/gumroad_web/live/review_live/review_component.html.heex
<div class="flex items-center gap-5">
<dt class="flex items-center gap-2">
	<div class="flex items-center">
		<div class="flex items-center">
		<%= for _ <- 1..round(@review.rating) do %>
			<!--
				Heroicon name: solid/star

				Active: "text-yellow-400", Inactive: "text-gray-200"
			-->
			<svg class="text-yellow-400 h-8 w-8 flex-shrink-0" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor" aria-hidden="true">
				<path d="M9.049 2.927c.3-.921 1.603-.921 1.902 0l1.07 3.292a1 1 0 00.95.69h3.462c.969 0 1.371 1.24.588 1.81l-2.8 2.034a1 1 0 00-.364 1.118l1.07 3.292c.3.921-.755 1.688-1.54 1.118l-2.8-2.034a1 1 0 00-1.175 0l-2.8 2.034c-.784.57-1.838-.197-1.539-1.118l1.07-3.292a1 1 0 00-.364-1.118L2.98 8.72c-.783-.57-.38-1.81.588-1.81h3.461a1 1 0 00.951-.69l1.07-3.292z" />
			</svg>
		<% end %>
		<%= for _ <- 1..round(5 - @review.rating) do %>
			<svg class="text-gray-200 h-8 w-8 flex-shrink-0" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor" aria-hidden="true">
				<path d="M9.049 2.927c.3-.921 1.603-.921 1.902 0l1.07 3.292a1 1 0 00.95.69h3.462c.969 0 1.371 1.24.588 1.81l-2.8 2.034a1 1 0 00-.364 1.118l1.07 3.292c.3.921-.755 1.688-1.54 1.118l-2.8-2.034a1 1 0 00-1.175 0l-2.8 2.034c-.784.57-1.838-.197-1.539-1.118l1.07-3.292a1 1 0 00-.364-1.118L2.98 8.72c-.783-.57-.38-1.81.588-1.81h3.461a1 1 0 00.951-.69l1.07-3.292z" />
			</svg>
			<% end %>
		</div>
	</div>
		<p class="text-gray-900 font-bold">
			<%= @review.rating %>
			<span class="sr-only"> out of 5 stars</span>
		</p>
</dt>
<dd class="flex gap-2 text-gray-500">
	<%= @review.description %>
</dd>
</div>

lib/gumroad_web/live/review_live/show.html.heex
<div class="grid gap-8">
  <h1 class="header">Show Review</h1>
  <%= if @live_action in [:edit] do %>
    <%= live_modal GumroadWeb.ReviewLive.FormComponent,
      id: @review.id,
      title: @page_title,
      action: @live_action,
      review: @review,
      return_to: Routes.review_show_path(@socket, :show, @review) %>
  <% end %>
  <div class="">
    <div class="px-4 py-5 sm:p-0">
      <dl class="sm:divide-y sm:divide-gray-200">
        <div class="py-4 sm:py-5 sm:grid sm:grid-cols-3 sm:gap-4 sm:px-6">
          <dt class="text-sm font-medium text-gray-500">
            Product Name
          </dt>
          <dd class="mt-1 text-sm text-gray-900 sm:mt-0 sm:col-span-2">
            <%= @review.product.name %>
          </dd>
        </div>
        <div class="py-4 sm:py-5 sm:grid sm:grid-cols-3 sm:gap-4 sm:px-6">
          <dt class="text-sm font-medium text-gray-500">
          Description
          </dt>
          <dd class="mt-1 text-sm text-gray-900 sm:mt-0 sm:col-span-2">
            <%= @review.description %>
          </dd>
        </div>
        <div class="py-4 sm:py-5 sm:grid sm:grid-cols-3 sm:gap-4 sm:px-6">
          <dt class="text-sm font-medium text-gray-500">
            Rating
          </dt>
          <dd class="mt-1 text-sm text-gray-900 sm:mt-0 sm:col-span-2">
            $<%= @review.rating %>
          </dd>
        </div>
      </dl>
    </div>
  </div>

  <div class="flex gap-5">
    <span class="button button-primary"><%= live_patch "Edit", to: Routes.review_show_path(@socket, :edit, @review) %></span>
    <span class="button button-secondary"><%= live_redirect "Back", to: Routes.review_index_path(@socket, :index) %></span>
  </div>
</div>